### ISSUE TITLE
ModuleNotFoundError: No module named 'coremltools.libmilstoragepython'

### ISSUE THREAD

**Issue by igrechuhin** [Vadbeg/colorization-coreml#1]
Hello. I tried to use your script, but it fails to load coremltools.libmilstoragepython.

➜  colorization-coreml git:(master) python3 run_colorization.py --data-root ./images
Traceback (most recent call last):
  File "/Users/myusername/Repo/colorization-coreml/run_colorization.py", line 5, in <module>
    import coremltools as ct
  File "/opt/homebrew/lib/python3.11/site-packages/coremltools/__init__.py", line 90, in <module>
    from . import converters
  File "/opt/homebrew/lib/python3.11/site-packages/coremltools/converters/__init__.py", line 7, in <module>
    from . import libsvm
  File "/opt/homebrew/lib/python3.11/site-packages/coremltools/converters/libsvm/__init__.py", line 7, in <module>
    from . import _libsvm_converter
  File "/opt/homebrew/lib/python3.11/site-packages/coremltools/converters/libsvm/_libsvm_converter.py", line 9, in <module>
    from coremltools.models import _METADATA_VERSION, _METADATA_SOURCE
  File "/opt/homebrew/lib/python3.11/site-packages/coremltools/models/__init__.py", line 37, in <module>
    from . import ml_program
  File "/opt/homebrew/lib/python3.11/site-packages/coremltools/models/ml_program/__init__.py", line 6, in <module>
    from . import compression_utils
  File "/opt/homebrew/lib/python3.11/site-packages/coremltools/models/ml_program/compression_utils.py", line 8, in <module>
    from coremltools.converters.mil.frontend.milproto.load import load as _milproto_to_pymil
  File "/opt/homebrew/lib/python3.11/site-packages/coremltools/converters/mil/frontend/milproto/__init__.py", line 6, in <module>
    from .load import load
  File "/opt/homebrew/lib/python3.11/site-packages/coremltools/converters/mil/frontend/milproto/load.py", line 27, in <module>
    from coremltools.libmilstoragepython import _BlobStorageReader as BlobReader
ModuleNotFoundError: No module named 'coremltools.libmilstoragepython'
➜  colorization-coreml git:(master) pip3 list
Package         Version
--------------- --------
click           8.1.3
contourpy       1.0.5
coremltools     6.0
cycler          0.11.0
fonttools       4.37.3
kiwisolver      1.4.4
matplotlib      3.6.0
mpmath          1.2.1
numpy           1.23.3
opencv-python   4.5.5.64
packaging       21.3
Pillow          9.2.0
pip             23.0.1
protobuf        3.20.1
pyparsing       3.0.9
python-dateutil 2.8.2
setuptools      65.6.3
six             1.16.0
sympy           1.11.1
TBB             0.2
tqdm            4.64.1
typer           0.6.1
wheel           0.38.4
➜  colorization-coreml git:(master)

**Comment by Vadbeg** [comment]
Hi! What OS do you have? As far as i know coremltools doesn't support model inference on Windows and Linux. Only MacOS

**Comment by Vadbeg** [comment]
Okay, found out what's the problem is about. 
coremltools==0.6.0 doesn't support python3.11. So you need to use python3.9/3.10.
https://github.com/apple/coremltools/issues/1730#issuecomment-1382615962

For development I've used python3.9.
```
virtualenv -p python3.9 .venv && source .venv/bin/activate
```

Thanks for finding this out! I've already updated README of the project.
